# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  Repository: repository  # github repositories
  About: about  # 关于
  Pwning: pwning

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home
  archives: icon-archive
  categories: icon-folder
  tags: icon-tag
  repository: icon-project
  pwning: icon-book
  about: icon-cup

site:
  favicon: /images/favicon.ico
  #manifest:
  site_verification:
#    google:
#    baidu:
#  google_analytics:
#  service_worker:

pagination:
  prev:
    alwayShow: true
  next:
    alwayShow: true

comment:
  type: # gitalk  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  livere:
    uid: # enter youyan uid
  gitalk: # gitalk. https://gitalk.github.io/
    owner: fengkx #必须. GitHub repository 所有者，可以是个人或者组织。
    admin: fengkx #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo: blog-comment #必须. GitHub repository.
    ClientID:  #必须. GitHub Application Client ID.
    ClientSecret:  #必须. GitHub Application Client `ecret.
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: false # Article reading statistic https://valine.js.org/visitor.html
    lang: en # Language of comment instruction. Default CH


github:
  username: sayoojbkumar

# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计

search: true # enable local search
toc: true
fancybox: true
license: 'This article is available under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener noreferrer">Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)</a> License'
footer:
#  custom:

profile:
  enabled: true # Whether to show profile bar
#  avatar: images/avatar.jpg
  gravatar: sayoojbkumar@gmail.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: Sayooj B Kumar
  author_title: Security Engineer @Cred | CTF'ing @teambi0s
  author_description: Die Hacking... 
  location: Bangalore, India
  follow: https://github.com/sayoojbkumar
  # Social Links
  social:
    links:
      github: https://github.com/sayoojbkumar
      twitter: https://twitter.com/_1nt3rc3pt0r_
      # facebook: /
      # dribbble: /
#      behance: https://www.behance.net/cofess
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false

projects:
    fengkx/NodeRSSBot: https://github.com/fengkx/NodeRSSBot
    fengkx/translator: https://github.com/fengkx/translator
    fengkx/cacheman-level: https://github.com/fengkx/cacheman-level

widgets:
#  - board
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

#widget behaivor
show_count: true

cdn:
  katex: //cdn.jsdelivr.net/npm/katex@0.9.0/dist/katex.min.css
  gitment: //cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css
  gitalk: //cdn.jsdelivr.net/npm/gitalk@1.4.0/dist/gitalk.min.css
  gitalk_js: //cdn.jsdelivr.net/npm/gitalk@1.5.2/dist/gitalk.min.js
  blueimp_md5: //cdn.jsdelivr.net/npm/blueimp-md5@2.10.0/js/md5.min.js
  valine: //cdn.jsdelivr.net/npm/valine@1.3.10/dist/Valine.min.js
  lightgallery_css: //cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/css/lightgallery.min.css
  lightgallery_js: //cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/js/lightgallery.min.js
  aplayer: //cdn.jsdelivr.net/npm/svelte-aplayer/dist/wc/svelte-aplayer.umd.js
